app/dash/routes.py
from flask import Blueprint
from imports import *

dash_bp = Blueprint("dash_bp", __name__, template_folder='templates', static_folder = 'static')

# Paul handles data for group tasks & their comments, as well as search results
paul = Taskdata()


#index

@dash_bp.route("/", methods=['GET', 'POST'])
def index():
    # task form
    task_form = GroupTaskForm()
    if task_form.validate_on_submit():
        return paul.post_new_task_and_redirect(task_form)
    
    # load group tasks
    tasks = paul.get_homepage_tasks()


    return render_template("index.html", tasks=tasks, task_form=task_form, get_poster_name=paul.get_poster_name )

#open up a task
@dash_bp.route("/group_task/<int:id>", methods=['GET', 'POST'])
@login_required
def group_task(id):
    comment_form = GroupTaskCommentForm()
    if comment_form.validate_on_submit():
        # print(comment_form.content.data)
        return paul.post_task_comment_and_redirect(comment_form, id)


    # TODO: pass all this to pual and let him handle it
    if request.method == 'POST':
        # Check which button was pressed and update task status accordingly
        if 'start' in request.form:
            paul.update_task_status(id, 1)  # Set status to 'In Progress'
        elif 'complete' in request.form:
            paul.update_task_status(id, 2)  # Set status to 'Completed'
        elif 'incomplete' in request.form:
            paul.update_task_status(id, 0)  # Set status to 'Not Started'

        return redirect(url_for('dash_bp.group_task', id=id))
    #

    comments = paul.get_task_comments(id)
    task = paul.get_task(id)
    name = paul.get_poster_name(task.poster_id)
    # print(comment_form.errors) # if form not validating

    comment_form.content.data = '' # not entirely neccessary, paul handles this
    return render_template("group_task.html", id=id, comments = comments, task = task, name=name, comment_form=comment_form, get_name = paul.get_poster_name)


# open a comment
@dash_bp.route("/comment/<int:id>", methods=['GET', 'POST'])
@login_required
def comment(id):
    comment_form = GroupTaskCommentForm()
    if comment_form.validate_on_submit():
        task_id = paul.get_comment(id).task_id
        return paul.post_threaded_comment_and_redirect(comment_form, id,task_id)
    comments = paul.get_threaded_comments(id)
    parent_comment = paul.get_comment(id)
    name = paul.get_poster_name(parent_comment.poster_id)
    task = paul.get_root_task(id)
    comment_form.content.data = ''
    return render_template("comment.html", id=id, comments=comments, parent_comment=parent_comment, comment_form=comment_form, name=name, task=task, get_name=paul.get_poster_name)


# Update task status
@dash_bp.route("/update_task_status/<int:id>/<status>", methods=['POST'])
@login_required
def update_task_status(id, status):
    task = paul.get_task(id)

    if task:
        task.status = int(status)
        db.session.commit()

    return redirect(url_for('dash_bp.group_task', id=id))

app/search/routes.py
from flask import Blueprint
from imports import *


search_bp = Blueprint("search_bp", __name__, template_folder='templates', static_folder = 'static')


paul = Taskdata()




@search_bp.route("/search", methods=['POST'])
@login_required
def search():
    search_form = SearchForm()
    tasks = GroupTasks.query
    if search_form.validate_on_submit():
        searched = search_form.searched.data
        tasks= tasks.filter((GroupTasks.content.like("%" + searched + "%"))).all()
        return render_template("search.html", search_form=search_form, searched=searched, tasks=tasks, get_name = paul.get_poster_name)

app/templates/base.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Jan24</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
        <link href="{{url_for('static', filename='css/styles.css')}}" rel="stylesheet">
      </head>
<body>
    {%include 'navbar.html'%}

    {%for m in get_flashed_messages()%}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
       {{m}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {%endfor%}


    {%block content%}
    {%endblock%}
</body>


</html>

app/templates/chart.html
{%extends base.html%}

{% block content%}




{%endblock%}

app/templates/comment.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-3">
{%if not parent_comment.parent_id == 0%}
<a href="{{url_for('dash_bp.comment', id=parent_comment.parent_id)}}"> <button type="button" class="btn btn-primary btn-sm">back</button></a>
{%else%}
<a href="{{url_for('dash_bp.group_task', id=task.id)}}"> <button type="button" class="btn btn-primary btn-sm">back</button></a>
{%endif%}
</div>

<div class="container mt-4">
    <h3>Task: {{ task.title }}</h3>

    <p>{{ task.content }}</p>
    <br><br>
    <p>Comment by: {{ name }}</p>
    <p style="max-width: 500px; word-wrap: break-word; width: 500px;">{{ parent_comment.content }}</p>

    <h4>Post a reply:</h4>
    <form method="POST" autocomplete="off">
        <div class="form-group">
            {{ comment_form.content.label(class="form-label") }}
            {{ comment_form.content(class="form-control") }}
        </div>

        {{ comment_form.submit(class="btn btn-secondary") }}
        {{ comment_form.csrf_token }}
        {{ comment_form.hidden_tag() }}

        <!-- If there is an error in the form validation -->
        {% if comment_form.errors %}
            <ul class="errors">
                {% for error in comment_form.errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    </form>

    <br><br>

    <div class="comments">
        {% for comment in comments %}
            <div class="card mb-2">
                <div class="card-body">
                    <h5 class="card-title">{{ get_name(comment.poster_id) }}</h5> 
                    <p class="card-text">{{ comment.content }}</p>
                    <p class="card-text"><small class="text-muted">{{ comment.date_posted.strftime('%Y-%m-%d %H:%M:%S') }}</small></p>
                    <small><a href="{{url_for('dash_bp.comment', id=comment.id)}}">reply</a></small>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

app/templates/group_task.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-4">
    <h2>{{ task.title }}</h2>
    <p>{{ name }}</p>

    <div class="card mb-4">
        <div class="card-body">
            <p class="card-text" style="max-width: 800px; word-wrap: break-word;">{{ task.content }}</p>
        </div>
    </div>

    <div class="status mb-4">
        <h4>Status:</h4>

        {% if task.status == 0 %}
            <span class="badge badge-warning" style="font-size: larger; color: red;">Not Started</span>
           
        {% elif task.status == 1 %}
            <span class="badge badge-info" style="font-size: larger; color: orange;">In Progress</span>
            
        {% elif task.status == 2 %}
            <span class="badge badge-success" style="font-size: larger; color: green;">Completed</span>
            
        {% endif %}

        <form method="POST" class="mb-4">
            <button type="submit" name="start" value="1" class="btn btn-success">Start</button>
            <button type="submit" name="complete" value="2" class="btn btn-primary">Complete</button>
            <button type="submit" name="incomplete" value="0" class="btn btn-danger">Mark Incomplete</button>
            {{ comment_form.csrf_token }}
        </form>
    </div>

    <form method="POST" class="mb-4">
        <div class="form-group">
            {{ comment_form.content.label(class="form-label") }}
            {{ comment_form.content(class="form-control") }}

            <!-- If there is an error in the form validation -->
            {% if comment_form.errors %}
                <ul class="errors">
                    {% for error in comment_form.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>

        {{ comment_form.submit(class="btn btn-secondary") }}
        {{ comment_form.csrf_token }}
        {{ comment_form.hidden_tag() }}
    </form>

    <div class="comments">
        {% for comment in comments %}
            <div class="card mb-2">
                <div class="card-body">
                    <h5 class="card-title">{{ get_name(comment.poster_id) }}</h5> 
                    <p class="card-text">{{ comment.content }}</p>
                    <p class="card-text"><small class="text-muted">{{ comment.date_posted.strftime('%Y-%m-%d %H:%M:%S') }}</small></p>
                    <small><a href="{{url_for('dash_bp.comment', id=comment.id)}}">reply</a></small>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-4">
    {% if current_user.is_authenticated %}
        <h2>Welcome, {{ current_user.name }}.</h2> <br><br>
        <h3>Post a Task</h3>
        <form method="POST" class="mb-4">
            {{ task_form.hidden_tag() }}
            
            <div class="form-group">
                {{ task_form.title.label(class="form-label") }}
                {{ task_form.title(class="form-control") }}
            </div>

            <div class="form-group">
                {{ task_form.content.label(class="form-label") }}
                {{ task_form.content(class="form-control") }}
            </div>

            {{ task_form.submit(class="btn btn-secondary") }}
        </form>

        <div class="list-group">
            {% for task in tasks %}
                <a href="{{ url_for('dash_bp.group_task', id=task.id)}}" class="list-group-item list-group-item-action">
                    <h4 class="mb-1">{{ task.title }}</h4>
                    
                    {% if task.status == 0 %}
                    <span class="badge badge-warning" style="color: red;">Not Started</span>
                {% elif task.status == 1 %}
                    <span class="badge badge-info" style="color: orange;">In Progress</span>
                {% elif task.status == 2 %}
                    <span class="badge badge-success" style="color: green;">Completed</span>
                {% endif %}
                    <p class="mb-1" style="max-width: 500px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;">{{ task.content }}</p>
                        &nbsp;| Posted by {{ get_poster_name(task.poster_id) }} on {{ task.date_posted.strftime('%Y-%m-%d %H:%M:%S') }}</small>
                </a>
            {% endfor %}
        </div>

</div>

{% else %}
    Please <a href="{{ url_for('auth_bp.login') }}">Login</a> <br>
    or <a href="{{ url_for('auth_bp.new_user') }}">Register</a>
{% endif %}

{% endblock %}

app/templates/login.html
{%extends 'base.html'%}

{% block content %}



{% if current_user.is_authenticated %}
  Hi {{ current_user.name }}!


{%else%}

<div class="shadow p-3 mb-5 bg-body-tertiary rounded">
    <h1>Login</h1>
    <form method="POST">
		{{ form.hidden_tag() }}

		{{ form.username.label(class="form-label") }}
		{{ form.username(class="form-control") }}
		<br/>
		{{ form.password.label(class="form-label") }}
		{{ form.password(class="form-control") }}
		<br/>

		{{ form.submit(class="btn btn-secondary") }}

    </form>
</div>

{%endif%}




{%endblock%}

app/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{{ url_for('dash_bp.index') }}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('auth_bp.new_user') }}">Register</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Authentication
            </a>
            <ul class="dropdown-menu">
              {%if not current_user.is_authenticated%}
                <li><a class="dropdown-item" href="{{ url_for('auth_bp.login') }}">Login</li>
                {%endif%}
                  {%if current_user.is_authenticated%}
              <li><a class="dropdown-item" href="{{url_for('auth_bp.logout')}}">Logout</a></li> 
              {%else%}
              <li><a class="nav-link disabled" href="#">Logout</a></li> 
              {%endif%}
              
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
          <li class="nav-item">
            {%if current_user.username == "admin"%}
            <li><a class="nav-link" href=#>Admin Console</a></li> 
            {%else%}
            <a class="nav-link disabled">Disabled</a>
            {%endif%}
          </li>
        </ul>
        <form method="POST" action="{{url_for('search_bp.search') }}" class="d-flex">
          {{search_form.hidden_tag()}}
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="searched">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>

app/templates/new_user.html
{%extends 'base.html'%}

{% block content %}

{%if name%}
    <h1>Hello {{name}} </h1>
    <!-- <img src="{{url_for('static', filename='images/dog.jpeg')}}"> -->

{%else%}

    <div class="shadow p-3 mb-5 bg-body-tertiary rounded">
        <h1>Register</h1>
        <form method="POST">
            {{ form.hidden_tag() }}

            {{ form.name.label(class="form-label") }}
            {{ form.name(class="form-control") }}
            <br/>
            {{ form.username.label(class="form-label") }}
            {{ form.username(class="form-control") }}
            <br/>

            {{ form.key.label(class="form-label") }}
            {{ form.key(class="form-control") }}
            <br/>
            
            {{ form.password_hash.label(class="form-label") }}
            {{ form.password_hash(class="form-control") }}
            <br/>

            {{ form.password_hash2.label(class="form-label") }}
            {{ form.password_hash2(class="form-control") }}
            <br/>

            {{ form.submit(class="btn btn-secondary") }}

        </form>
    </div>
    <br><br>

    Existing Users: <br><br>
    {%for u in existing_users%}
    <tr>
        <td>{{ u.username }}. {{ u.name }}. {{u.id}}</tr> <br>
        </tr>
    {%endfor%}

{%endif%}



{% endblock %}

app/templates/search.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-4">
    <h2>Results for: {{ searched }}</h2>

    <br>

    {% if tasks %}
        <div class="list-group">
            {% for task in tasks %}
                <a href="{{ url_for('dash_bp.group_task', id=task.id)}}" class="list-group-item list-group-item-action">
                    <h4 class="mb-1">{{ task.title }}</h4>

                    {% if task.status == 0 %}
                        <span class="badge badge-warning" style="font-size: larger; color: red;">Not Started</span>
                       
                    {% elif task.status == 1 %}
                        <span class="badge badge-info" style="font-size: larger; color: orange;">In Progress</span>
                        
                    {% elif task.status == 2 %}
                        <span class="badge badge-success" style="font-size: larger; color: green;">Completed</span>
                        
                    {% endif %}
                    <p class="mb-1" style="max-width: 500px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;">{{ task.content }}</p>
                    <small class="text-muted">Posted by {{ get_name(task.poster_id) }} on {{ task.date_posted.strftime('%Y-%m-%d %H:%M:%S') }}</small>
                </a>
            {% endfor %}
        </div>
    {% else %}
        <p>No Results</p>
    {% endif %}
</div>

{% endblock %}